### ISSUE TITLE
Install script not compatible with current dev (and future version of Kresus)

### ISSUE THREAD

**Issue by ZeHiro** [LowMem/kresus_ynh#3]
Next version of Kresus needs to be passed a parameter to handle correctly the routing of the client when it is not served on a sub domain. 
When launching kresus, the parameter KRESUS_URL_PREFIX to be set to the path at which is served kresus. See https://framagit.org/bnjbvr/kresus/blob/master/README.md

**Comment by LowMem** [comment]
It seems to me that there is no need to define a ``KRESUS_URL_PREFIX``: YUNoHost uses nginx as a frontend web server. So that once authentication is made, external requests are "reverse proxified" to ``http://127.0.0.1:9876/``. (Please check [nginx configuration file](https://github.com/LowMem/kresus_ynh/blob/master/conf/nginx.conf).)

I close this issue, feel free to reopen it if I am mistaken (please note that adding such parameter to [systemd service](https://github.com/LowMem/kresus_ynh/blob/master/conf/kresus.service) prevented kresus service to start. :sweat: )

**Comment by ZeHiro** [comment]
In fact you have to set KRESUS_URL_PREFIX to the value here : 
https://github.com/LowMem/kresus_ynh/blob/master/manifest.json#L36

It is necessary for next release (not yet published), otherwise the routing of the app won't work, currently, it is not necessary (using install from npm), but it will.

**Comment by Phyks** [comment]
Next release is published now :)

**Comment by LowMem** [comment]
Is this still current ?

(If so, please re-open this issue.)

**Comment by ZeHiro** [comment]
It is done with the config file in the current version of the packet. It could be closed. Thanks
